# Generated by Django 2.2.24 on 2023-04-08 22:00

from django.db import migrations


def create_a_value_for_a_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_building_year = 2015
    for flat in Flat.objects.all():
        if flat.construction_year >= new_building_year:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(create_a_value_for_a_building),
    ]
