# Generated by Django 2.2.24 on 2023-04-12 15:39

from django.db import migrations
import phonenumbers
from phonenumbers import NumberParseException


def create_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    all_flat = Flat.objects.all()
    for flat in all_flat.iterator():
        try:
            if not flat.owners_phonenumber:
                continue
            number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            number_e164_f = phonenumbers.format_number(number, phonenumbers.PhoneNumberFormat.E164)
            if not phonenumbers.is_valid_number(number):
                continue
            flat.owner_pure_phone = number_e164_f
            flat.save()
        except NumberParseException:
            continue


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    all_flat = Flat.objects.all()
    for flat in all_flat.iterator():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230412_1833'),
    ]

    operations = [
        migrations.RunPython(create_owner_pure_phone),
    ]
