# Generated by Django 2.2.24 on 2023-04-12 18:34

from django.db import migrations, IntegrityError


def copy_flat_to_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    try:
        for flat in Flat.objects.all():
            obj, created = Owner.objects.get_or_create(owner=flat.owner,
                                                       owners_phonenumber=flat.owners_phonenumber,
                                                       owner_pure_phone=flat.owner_pure_phone,
                                                       )
            obj.apartments_in_the_property.add(flat)
    except IntegrityError:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_owners),
    ]
