# Generated by Django 2.2.24 on 2023-04-12 18:34

from django.db import migrations, IntegrityError


def copy_flat_to_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    all_flat = Flat.objects.all()
    try:
        for flat in all_flat.iterator():
            obj, created = Owner.objects.get_or_create(full_name=flat.owner,
                                                       number=flat.owners_phonenumber,
                                                       pure_phone=flat.owner_pure_phone,
                                                       )
            obj.apartment.add(flat)
    except IntegrityError:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_owners),
    ]
