# Generated by Django 2.2.24 on 2023-04-13 09:12

from django.db import migrations


def remove_field_flat_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.owners_phonenumber = None
        flat.owner = None
        flat.save()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230413_1212'),
    ]

    operations = [
        migrations.RunPython(remove_field_flat_to_owners),
    ]
