# Generated by Django 2.2.24 on 2023-04-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230413_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='apartments_in_the_property',
        ),
        migrations.AddField(
            model_name='owner',
            name='apartment',
            field=models.ManyToManyField(related_name='apartments_owners', to='property.Flat', verbose_name='Апартаменты в собственности'),
        ),
    ]
