# Generated by Django 2.2.24 on 2023-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20230413_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='apartment',
            field=models.ManyToManyField(related_name='apartments', to='property.Flat', verbose_name='Апартаменты в собственности'),
        ),
    ]
