# Generated by Django 2.2.24 on 2023-04-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20230413_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='apartment',
            new_name='apartments',
        ),
    ]
